name: Daily Movie Tweet

on:
  schedule:
    - cron: '0 7 * * *'  # Runs at 07:00 UTC (Same as Lisbon Time)
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # Prevents default token usage

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        env:
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          DAY_COUNT: ${{ vars.DAY_COUNT }}
        run: python main.py

      - name: Commit and push state.json
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Fetch the latest `state` branch before pushing
          git fetch origin state || echo "State branch does not exist yet"

          # Create `state` branch if it doesn't exist
          git checkout -b state || git checkout state

          # Merge remote changes to avoid conflicts
          git pull origin state --rebase

          # Add and commit state.json
          git add state.json
          git commit -m "Update LAST_MOVIE"

          # Push changes with force-with-lease to avoid overwriting
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git state --force-with-lease
