name: Daily Answer Tweet

on:
  schedule:
    - cron: '0 18 * * *'  # Runs at 18:00 UTC (Same as 6 PM Lisbon time)
  workflow_dispatch:

jobs:
  tweet_answer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run answer script
        env:
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          DAY_COUNT: ${{ env.DAY_COUNT }}
          LAST_MOVIE: ${{ env.LAST_MOVIE }}
        run: python post_answer.py
