name: Daily Answer Tweet

on:
  schedule:
    - cron: '0 18 * * *'  # Runs at 18:00 UTC (Same as 6 PM Lisbon time)
  workflow_dispatch:

jobs:
  tweet_answer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # Disable default GitHub token

      - name: Set up Git authentication
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git

      - name: Fetch the latest `state.json`
        run: |
          git fetch origin state || echo "State branch does not exist yet"
          git checkout -b state || git checkout state
          git pull origin state --rebase

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run answer script
        env:
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
        run: python post_answer.py
